---
version: '3.3'
volumes:
  database_data:
    driver: local

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    image: producer1:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      HOST_IP: Istanbul
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    restart: always

  producer1:
      image: producer1:latest
      depends_on:
        - kafka
      ports:
        - "8090:8090"
      environment:
        HOST_IP: Tokyo
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      restart: always

  producer2:
     image: producer1:latest
     depends_on:
       - kafka
     ports:
       - "9000:9000"
     environment:
       HOST_IP: Moscow
       SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
     restart: always
  producer3:
      image: producer1:latest
      depends_on:
        - kafka
      ports:
        - "9010:9010"
      environment:
        HOST_IP: Beijing
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      restart: always

  producer4:
     image: producer1:latest
     depends_on:
       - kafka
     ports:
       - "9020:9020"
     environment:
       HOST_IP: London
       SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
     restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - database_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - database_data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

#
#  consumer:
#    image: consumer1:latest
#    ports:
#      - "9030:9030"
#    depends_on:
#      - producer
#      - kafka
#    environment:
#      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
#    restart: always